--                          CUSTOMER SPECIFITCATION
CREATE OR REPLACE PACKAGE customer AS
PROCEDURE register(firstName_in IN CUSTOMERS.FIRSTNAME%TYPE,lastName_in CUSTOMERS.LASTNAME%TYPE, phone_in CUSTOMERS.PHONE%TYPE, address_in CUSTOMERS.ADDRESS%TYPE,
    city_in IN CUSTOMERS.CITY%TYPE, state_in IN CUSTOMERS.STATE%TYPE);
PROCEDURE search(origin_in FLIGHTS.ORIGIN%TYPE, destination_in FLIGHTS.DESTINATION%TYPE, flightdate_in FLIGHTS.FLIGHTDATE%TYPE);
PROCEDURE makeReservation(custID_in IN CUSTOMERS.CUSTOMERID%TYPE, flightID_in IN FLIGHTS.FLIGHTID%TYPE, seats_in IN FLIGHTS.SEATS%TYPE);
PROCEDURE viewReservation(customerID_in CUSTOMERS.CUSTOMERID%TYPE);
END;
/



